from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from backend.utils.file_utils import get_report_path, get_graph_path


def generate_report(video_id: str, viscosity: float, a: float, b: float,
                    r_squared: float = None) -> Path:
    report_path = get_report_path(video_id)
    graph_path = get_graph_path(video_id)

    if not graph_path.exists():
        raise FileNotFoundError(f"Graph not found for video {video_id}")

    c = canvas.Canvas(str(report_path), pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 20)
    title_y = height - 1 * inch
    c.drawCentredString(width / 2, title_y, "Viscosity Analysis Report")

    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, title_y - 0.3 * inch, f"Video ID: {video_id}")

    graph_y = title_y - 1 * inch
    graph_width = 6 * inch
    graph_height = 4.5 * inch

    try:
        img_reader = ImageReader(graph_path)
        c.drawImage(
            img_reader,
            (width - graph_width) / 2,
            graph_y - graph_height,
            width=graph_width,
            height=graph_height,
            preserveAspectRatio=True,
        )
    except Exception as e:
        c.setFont("Helvetica", 10)
        c.drawString(1 * inch, graph_y - 0.5 * inch, f"Error loading graph: {e}")

    results_y = graph_y - graph_height - 0.5 * inch

    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, results_y, "Analysis Results")

    c.setFont("Helvetica", 12)
    line_height = 0.25 * inch

    results_y -= line_height * 1.5
    c.drawString(
        1 * inch,
        results_y,
        f"Power-Law Equation: h(t) = {a:.6f} × t^{b:.6f}",
    )

    if r_squared is not None:
        results_y -= line_height
        c.drawString(1 * inch, results_y, f"R² (Goodness of Fit): {r_squared:.6f}")

    results_y -= line_height * 1.5
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, results_y, f"Calculated Viscosity: {viscosity:.6f} Pa·s")

    c.setFont("Helvetica", 8)
    c.drawString(1 * inch, 0.5 * inch, "Generated by Video Analysis System")

    c.save()
    return report_path    