"""
Report generation service for creating PDF reports.
"""
from pathlib import Path
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from PIL import Image

from backend.core.config import settings
from backend.utils.file_utils import get_report_path, get_graph_path


def generate_report(video_id: str, viscosity: float, slope: float, intercept: float, 
                   r_value: float = None) -> Path:
    """
    Generate a PDF report with graph, equation, and viscosity result.
    
    Args:
        video_id: Unique video identifier
        viscosity: Calculated viscosity value (Pa·s)
        slope: Slope from linear regression
        intercept: Intercept from linear regression
        r_value: Optional correlation coefficient
    
    Returns:
        Path to the generated PDF file
    """
    report_path = get_report_path(video_id)
    graph_path = get_graph_path(video_id)
    
    if not graph_path.exists():
        raise FileNotFoundError(f"Graph not found for video {video_id}")
    
    # Create PDF canvas
    c = canvas.Canvas(str(report_path), pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    title_y = height - 1 * inch
    c.drawCentredString(width / 2, title_y, "Viscosity Analysis Report")
    
    # Video ID
    c.setFont("Helvetica", 10)
    c.drawString(1 * inch, title_y - 0.3 * inch, f"Video ID: {video_id}")
    
    # Insert graph image
    graph_y = title_y - 1 * inch
    graph_width = 6 * inch
    graph_height = 4.5 * inch
    
    try:
        # Load and insert graph image
        img = Image.open(graph_path)
        img_reader = ImageReader(graph_path)
        c.drawImage(img_reader, (width - graph_width) / 2, graph_y - graph_height, 
                   width=graph_width, height=graph_height, preserveAspectRatio=True)
    except Exception as e:
        c.setFont("Helvetica", 10)
        c.drawString(1 * inch, graph_y - 0.5 * inch, f"Error loading graph: {str(e)}")
    
    # Results section
    results_y = graph_y - graph_height - 0.5 * inch
    
    c.setFont("Helvetica-Bold", 14)
    c.drawString(1 * inch, results_y, "Analysis Results")
    
    c.setFont("Helvetica", 12)
    line_height = 0.25 * inch
    
    # Regression equation
    results_y -= line_height * 1.5
    c.drawString(1 * inch, results_y, f"Regression Equation: h(t) = {slope:.6f} × t + {intercept:.6f}")
    
    # Correlation coefficient (if provided)
    if r_value is not None:
        results_y -= line_height
        c.drawString(1 * inch, results_y, f"Correlation Coefficient (R): {r_value:.6f}")
    
    # Viscosity result
    results_y -= line_height * 1.5
    c.setFont("Helvetica-Bold", 12)
    c.drawString(1 * inch, results_y, f"Calculated Viscosity: {viscosity:.6f} Pa·s")
    
    # Footer
    c.setFont("Helvetica", 8)
    c.drawString(1 * inch, 0.5 * inch, "Generated by Video Analysis System")
    
    # Save PDF
    c.save()
    
    return report_path

